### ISSUE TITLE
Terria stops fetching wps result when fetching wp-result fails

### ISSUE THREAD

**Issue by pindge** [opendatacube/datacube-wps#10]
### Expected behaviour
Terria should only stop the process at 

```
<ows:ExceptionText>Process failed, please check server error log</ows:ExceptionText>
```

### Actual behaviour

When terria continuously fetch for wps result from aws s3 while the xml file has line 
```
<wps:ProcessStarted percentCompleted="0">PyWPS Process started</wps:ProcessStarted>
```
If the query fails maybe S3 is unreachable or network issue, then Terria displays an error message  and below is network log

![image](https://user-images.githubusercontent.com/24644475/73810264-0cdf2b80-482a-11ea-9230-108798e333ec.png)

The error displayed on Terria
![image](https://user-images.githubusercontent.com/24644475/73811124-bd4e2f00-482c-11ea-8af0-b860afc8f46d.png)

### Steps to reproduce the behaviour

This behaviour is not consistent. 

1. http://terria-cube.terria.io/
2. add data > DEA Development > Fractional Cover > Fractional Cover Daily Observations >Fractional Cover Polygon Drill
3. Click to draw polygon and draw a large shape
4. Put start date and end date over 20 years span

**Comment by uchchwhash** [comment]
Unfortunately this sounds more like a terria bug that a WPS bug. Closing.
