### ISSUE TITLE
Prometheus and App start up failure

### ISSUE THREAD

**Issue by whatnick** [opendatacube/datacube-wps#117]
### Expected behaviour
Prometheus metrics exist

### Actual behaviour
Intermittently prometheus interferes with app startup
Please add error log here @mmochan

**Comment by benjimin** [comment]
So this app is supposed to use `prometheus-flask-exporter`. Usually this will expose such metrics as a cumulative histogram _flask_http_request_duration_seconds_, and counts _flask_http_request_total_ and  _flask_http_request_exceptions_total_. These metrics seem intended to be labelled by endpoint, and with a further custom metric intended to provide a full url? (If deployed in a kubernetes cluster that uses e.g. cAdvisor, then there will additionally be general metrics available elsewhere such as the container CPU time, memory and data transfer.) 

The metrics are usually exposed at `/metrics`, not sure yet how this interacts if other OWS services are deployed to the same domain as the `/wps`? Apparently the exporter needs additional complexity to handle multiprocessing, gunicorn, and WSGI..

**Comment by benjimin** [comment]
Prometheus metrics appear to be working now..
