### ISSUE TITLE
Enable processing integration to WPS

### ISSUE THREAD

**Issue by pindge** [opendatacube/datacube-wps#27]
**Issue**
datacube-wps has two built-in processes 
```
processes = [
    WofsDrill(),
    FcDrill()
]
```
https://github.com/opendatacube/datacube-wps/tree/master/processes

To add a new process require in-depth knowledge about WPS

**Goal**
Significantly improve developer experience for wps process add-on

**Solution**
- Document required input for process add-on
- simplify current wps process structure for easy integration

**Comment by uchchwhash** [comment]
I feel like this has been addressed already to an extent. Closing.
