### ISSUE TITLE
Replace Chromium based SVG generation with more Pure Python version

### ISSUE THREAD

**Issue by whatnick** [opendatacube/datacube-wps#59]
### Expected behaviour
No heavy chromium dependency for SVG generation

### Actual behaviour
Chromium is needed in the SVG generation pipeline leading to heavy docker image, unexpected vulnerabilities and slower builds. See commit [here](https://github.com/opendatacube/datacube-wps/commit/753a8de5e3d16b9897adc3ace8deec985ca84448)

### Steps to reproduce the behaviour
- SVG generation fails without Chromium
- Replace with Python svgwriter : https://github.com/mozman/svgwrite

**Comment by uchchwhash** [comment]
Closing this as we have replaced chrome+selenium with nodejs+canvas 😄.

Lesser of the two evils and stuff.
