### ISSUE TITLE
WPS to receive arbitrary parameters

### ISSUE THREAD

**Issue by emmaai** [opendatacube/datacube-wps#71]
### Expected behaviour
`reqeust_handler` and `query_handler` to receive parameter(s) `**kwargs` such that those can be passed to computation `data_process` later

### Actual behaviour
Only pre-defined parameters are accepted, e.g., currently `time` and `feature`

### Steps to reproduce the behaviour

N/A

**Comment by uchchwhash** [comment]
I am thinking a special parameter called `parameters` that is of JSON type and we can put the processing customizations there.

**Comment by emmaai** [comment]
Any form of passing extra parameters is fine for me.
