### ISSUE TITLE
WPS request kills wps process

### ISSUE THREAD

**Issue by pindge** [opendatacube/datacube-wps#8]
### Expected behaviour
WPS to process request successfully

### Actual behaviour

gunicorn worker dies and kubectl get logs returns nothing - maybe the pod is dead
```
[2020-02-03 22:26:36 +0000] [10] [CRITICAL] WORKER TIMEOUT (pid:13)
[2020-02-03 22:27:22 +0000] [7248] [INFO] Booting worker with pid: 7248
```
Terria displays this message
![image](https://user-images.githubusercontent.com/24644475/73696966-8b0bd700-4731-11ea-9bbe-dd83e95905a8.png)

### Steps to reproduce the behaviour

1. http://terria-cube.terria.io/
2. add data > DEA Development > Fractional Cover > Fractional Cover Daily Observations >Fractional Cover Polygon Drill
3. Click to draw polygon and draw a large shape
4. Put start date and end date over 20 years span

**Comment by pindge** [comment]
Possible solution:

- Split wps web service layer and WPS processing layer
- WPS web service layer only does one job that is to receive wps request, validates the request then forward the request to SQS
- WPS processing layer receives job, checks for data-size and scale number of pods based on predefined calculation resource breakdown
- All results to S3

**Comment by uchchwhash** [comment]
We are going to pursue something similar to the proposed solution here when we deal with larger polygons for our internal processing. But this error is fixed now.
